name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ["**"]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, sqlite3, pdo_sqlite, dom, curl, fileinfo
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
          # Use SQLite for simplicity in CI
          mkdir -p database
          touch database/database.sqlite
          sed -i "s/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/" .env
          sed -i "s/^DB_DATABASE=.*/DB_DATABASE=.\/database\/database.sqlite/" .env || echo "DB_DATABASE=.\/database\/database.sqlite" >> .env

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests (Pest)
        run: ./vendor/bin/pest -q

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
